[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RPG Creator"
authors = [{name = "Ward", email = "ward727a@gmail.com"}]
dynamic = ["version", "description"]
